/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/audit': RouteRecordInfo<'/admin/audit', '/admin/audit', Record<never, never>, Record<never, never>>,
    '/admin/message': RouteRecordInfo<'/admin/message', '/admin/message', Record<never, never>, Record<never, never>>,
    '/admin/songManage': RouteRecordInfo<'/admin/songManage', '/admin/songManage', Record<never, never>, Record<never, never>>,
    '/box': RouteRecordInfo<'/box', '/box', Record<never, never>, Record<never, never>>,
    '/gift': RouteRecordInfo<'/gift', '/gift', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/songs': RouteRecordInfo<'/songs', '/songs', Record<never, never>, Record<never, never>>,
  }
}
