FROM node:20-alpine AS build

WORKDIR /app
RUN mkdir -p /server/static/frontend

COPY frontend/package.json /app/package.json
RUN npm install
COPY frontend /app
RUN npm run build

FROM nginx:1.27-alpine
COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /server/static/frontend /usr/share/nginx/html/static/frontend
COPY server/static/backgrounds /usr/share/nginx/html/static/backgrounds
EXPOSE 80
